Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-04, with the labels that each got.

#8 Refactor netpol
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/networkpolicy.go
  pkg/networkpolicy/networkpolicy_test.go
Labels: size/XL, approved, cncf-cla: yes

#11 Fix logging
  pkg/networkpolicy/networkpolicy.go
  pkg/networkpolicy/packet.go
Labels: approved, cncf-cla: yes, size/XS

#13 drop iptables support
  cmd/main.go
  go.mod
  go.sum
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/networkpolicy_test.go
Labels: approved, cncf-cla: yes, size/L

#14 networkpolicy: Move subject filtering logic to getNetworkPoliciesForPod.
  pkg/networkpolicy/networkpolicy.go
Labels: approved, size/M, cncf-cla: yes, lgtm

#9 add admin and baseline network policy
  .github/workflows/npa.yml
  cmd/main.go
  go.mod
  go.sum
  install-anp.yaml
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/controller_test.go
  pkg/networkpolicy/networkpolicy.go
  pkg/networkpolicy/networkpolicy_test.go
  pkg/networkpolicy/networkpolicyapi.go
  pkg/networkpolicy/networkpolicyapi_test.go
  pkg/networkpolicy/packet.go
Labels: approved, size/XXL, cncf-cla: yes

#16 Release 0.2.0
  README.md
  install-anp.yaml
  install.yaml
Labels: approved, cncf-cla: yes

#18 Define Goals and not Goals of the project
  README.md
Labels: approved, cncf-cla: yes, size/S, lgtm
