Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-06, with the labels that each got.

#38 Bump distroless-iptables to v0.5.5
  Dockerfile
Labels: approved, cncf-cla: yes, size/XS, lgtm

#39 Only process traffic impacted by network policies
  cmd/main.go
  install-anp.yaml
  install.yaml
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/networkpolicy.go
Labels: approved, cncf-cla: yes, size/L

#42 use v0.3.0 for install manifests
  install-anp.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/XS

#44 don't use obscure env variables and use flags
  cmd/main.go
  go.mod
  go.sum
  install-anp.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/S

#45 bump install manifest to v0.4.0
  install-anp.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/XS
