Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-11, with the labels that each got.

#119 [Docs] comment on udp and effected pods in readme
  README.md
Labels: approved, cncf-cla: yes, size/XS, ok-to-test, lgtm

#50 Use structured logging
  cmd/main.go
  go.mod
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/networkpolicy.go
  pkg/networkpolicy/networkpolicy_test.go
  pkg/networkpolicy/networkpolicyapi.go
  pkg/networkpolicy/networkpolicyapi_test.go
  pkg/networkpolicy/packet.go
Labels: approved, cncf-cla: yes, size/L, lgtm

#115 Give metrics and logging a verdict dimension
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/metrics.go
Labels: approved, cncf-cla: yes, size/S, ok-to-test, lgtm
