Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-10, with the labels that each got.

#93 Fix small typo in README.md
  README.md
Labels: approved, cncf-cla: yes, size/XS, ok-to-test, lgtm

#95 Workaround dns kernel bug
  cmd/main.go
  pkg/networkpolicy/controller.go
Labels: approved, cncf-cla: yes, size/L

#97 update install manifests to 0.6.0
  install-anp.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/XS

#101 Update install-anp.yaml
  install-anp.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#102 Update install.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#106 Allow to configure the nftables name and implement defaulting in the config data structure
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/controller_test.go
Labels: approved, size/M, cncf-cla: yes, lgtm

#107 Add helm chart.
  README.md
  charts/kube-network-policies/.helmignore
  charts/kube-network-policies/Chart.yaml
  charts/kube-network-policies/templates/_helpers.tpl
  charts/kube-network-policies/templates/daemonset.yaml
  charts/kube-network-policies/templates/serviceaccount.yaml
  charts/kube-network-policies/values.yaml
Labels: approved, cncf-cla: yes, size/L, lgtm
