Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-07, with the labels that each got.

#53 move nftables creation inside the controller constructor
  cmd/main.go
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/controller_test.go
  pkg/networkpolicy/networkpolicy_test.go
  pkg/networkpolicy/networkpolicyapi_test.go
Labels: approved, size/M, cncf-cla: yes, lgtm

#51 Parse IPv6 extension headers
  pkg/networkpolicy/packet.go
  pkg/networkpolicy/packet_test.go
  pkg/networkpolicy/test-data/tcp-ipv4.pcap
  pkg/networkpolicy/test-data/udp.pcap
Labels: approved, cncf-cla: yes, size/L, lgtm

#54 Process packets only on the POSTROUTING hook (before SNAT)
  .github/workflows/e2e.yml
  .github/workflows/npa.yml
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/networkpolicy.go
Labels: approved, size/M, cncf-cla: yes

#57 Update install-anp.yaml to use 0.5.0
  install-anp.yaml
Labels: approved, cncf-cla: yes, size/XS

#56 Update install.yaml to use 0.5.0
  install.yaml
Labels: approved, cncf-cla: yes, size/XS

#58 add gitignore
  .gitignore
Labels: approved, cncf-cla: yes, size/S, lgtm

#64 allow to run kind on prow CI
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, size/L

#66 node local traffic is not processed by network policies
  hack/ci/e2e.sh
  pkg/networkpolicy/controller.go
Labels: approved, cncf-cla: yes, size/S, lgtm

#67 automate image building
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm
