Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2024-08, with the labels that each got.

#71 use different image for building
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#72 chore: using self docker builder for multi-platform images.
  Makefile
  cloudbuild.yaml
  hack/init-buildx.sh
Labels: approved, size/M, cncf-cla: yes, ok-to-test, lgtm

#73 chore: change env IMAGE to KNP_IMAGE for build image.
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS, ok-to-test, lgtm
