Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2025-04, with the labels that each got.

#157 Admin Network Policies: NPEP-133: Domain Names Selector for Egress Traffic
  .github/workflows/bats.yml
  .github/workflows/e2e.yml
  .github/workflows/npa.yml
  .gitignore
  cmd/main.go
  go.mod
  go.sum
  install-anp.yaml
  install.yaml
  pkg/networkpolicy/controller.go
  pkg/networkpolicy/dnsagent.go
  pkg/networkpolicy/dnsagent_test.go
  pkg/networkpolicy/domainmap.go
  pkg/networkpolicy/domainmap_test.go
  pkg/networkpolicy/networkpolicyapi.go
  pkg/networkpolicy/networkpolicyapi_test.go
  pkg/networkpolicy/nri.go
  tests/README.md
  tests/e2e.bats
  tests/setup_suite.bash
Labels: approved, size/XXL, cncf-cla: yes

#160 Liveness probes
  pkg/networkpolicy/dnsagent.go
  tests/e2e.bats
  tests/setup_suite.bash
Labels: approved, size/M, cncf-cla: yes

#163 Add uninstall steps and nftables cleanup note to README
  README.md
Labels: approved, cncf-cla: yes, size/S, ok-to-test, lgtm

#164 Fix graceful shutdown: handle SIGTERM properly to cleanup resources
  cmd/main.go
  pkg/networkpolicy/controller.go
Labels: approved, cncf-cla: yes, size/S, ok-to-test, lgtm
