Repository kubernetes-sigs/kube-network-policies, pull requests merged in 2025-08, with the labels that each got.

#178 remove cleanup nftable notice from readme
  README.md
Labels: approved, cncf-cla: yes, size/XS, ok-to-test, lgtm

#202 decouple Interfaces from Implementation
  cmd/main.go
  pkg/api/interfaces.go
  pkg/dataplane/controller_test.go
  pkg/networkpolicy/adminnetworkpolicy.go
  pkg/networkpolicy/adminnetworkpolicy_test.go
  pkg/networkpolicy/baselineadminnetworkpolicy.go
  pkg/networkpolicy/baselineadminnetworkpolicy_test.go
  pkg/networkpolicy/engine.go
  pkg/networkpolicy/engine_test.go
  pkg/networkpolicy/logging.go
  pkg/networkpolicy/networkpolicy.go
  pkg/networkpolicy/networkpolicy_test.go
Labels: approved, cncf-cla: yes, size/L

#203 avoid kindnet network policies
  .github/workflows/e2e.yml
  .github/workflows/npa.yml
  hack/ci/e2e.sh
  tests/setup_suite.bash
Labels: approved, cncf-cla: yes, size/S

#206 allow to pass kubeconfig as flag
  cmd/main.go
Labels: approved, cncf-cla: yes, size/S

#208 print version at start
  pkg/cmd/cmd.go
Labels: approved, cncf-cla: yes, size/S

#199 Cluster Network Policy
  Makefile
  cmd/kube-network-policies/npa-v1alpha2/main.go
  go.mod
  go.sum
  install-cnp.yaml
  pkg/networkpolicy/networkpolicy.go
  plugins/npa-v1alpha2/clusternetworkpolicy.go
  plugins/npa-v1alpha2/clusternetworkpolicy_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm

#226 Fix push for npa-v1alpha2 as it was only building before
  Makefile
Labels: approved, cncf-cla: yes, size/XS, lgtm

#228 fix kube-iptracker builder
  Dockerfile.iptracker
Labels: approved, cncf-cla: yes, size/XS

#229 Bump images to newly released v0.9.1
  install-anp.yaml
  install-cnp.yaml
  install-iptracker.yaml
  install.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm
